### ISSUE TITLE
Assertion failure:  Bin -> hex with window

### ISSUE THREAD

**Issue by zathras** [zathras/jrpn#12]
Start with this the below state, then do 20 window ">" operations, then switch to hex.

Result:  
flutter: Unexpected exception RangeError (index): Invalid value: Not in inclusive range 0..13: -7

#0      List.[] (dart:core-patch/growable_array.dart:254:60)
#1      DisplayModel.current (package:jrpn/m/model.dart:1022:35)
#2      Model._newLcdContents (package:jrpn/m/model.dart:669:68)
#3      DisplayModel.update (package:jrpn/m/model.dart:1090:33)
#4      DisplayModel.displayX (package:jrpn/m/model.dart:1131:7)
#5      Model.displayMode= (package:jrpn/m/model.dart:551:15)
#6      Operations.hex.<anonymous closure> (package:jrpn/c/operations.dart:111:28)
...

Probably just need to reset window when switching base.

{"version":1,"settings":{"menuEnabled":false,"windowEnabled":true,"euroComma":false,"hideComplement":false,"showWordSize":false,"showAccelerators":true,"systemOverlaysDisabled":false,"orientation":0},"displayMode":"b","integerSignMode":"2","wordSize":56,"stack":["ffffffffffffe6","c3111111","0","0"],"lastX":"0","flags":[false,false,false,false,false,false],"memory":{"storage":"0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","program":{"lines":0,"currentLine":0,"returnStack":[0,0,0,0],"returnStackPos":-1},"I":"0"}}

**Comment by zathras** [comment]
Fixed by https://github.com/zathras/jrpn/commit/ee47fba5b2db1bf4ed0227a77db7e09c6db5a0fb

**Comment by zathras** [comment]
Fix published: https://github.com/zathras/jrpn/releases/tag/2.0.1
