### ISSUE TITLE
GSB error.

### ISSUE THREAD

**Issue by ronmelvin** [zathras/jrpn#13]
Linux version 2.0.1.

Press "GSB" then "A"

On my real 16C I get "Error   4"

On jrpn, display doesn't change, but there is a stacktrace shown on terminal:
-> ./jrpn 
flutter: IntegerDivisionByZeroException
flutter: #0      ProgramMemory.goto (package:jrpn/m/memory.dart)
flutter: #1      ProgramMemory.gosub (package:jrpn/m/memory.dart:497)
flutter: #2      GosubArgInputState.handleGosubEntryDone (package:jrpn/c/states.dart:793)
flutter: #3      Resting.gosubEntryDone (package:jrpn/c/states.dart:379)
flutter: #4      GosubArgInputState.done (package:jrpn/c/states.dart:774)
flutter: #5      ArgInputState._gotNumber (package:jrpn/c/states.dart:719)
flutter: #6      ArgInputState.buttonDown (package:jrpn/c/states.dart:698)
flutter: #7      Controller.buttonDown (package:jrpn/c/controller.dart:98)
flutter: #8      RealController.buttonDown (package:jrpn/c/controller.dart:217)
flutter: #9      CalculatorButtonState.build.<anonymous closure> (package:jrpn/v/buttons.dart:1074)
flutter: #10     TapGestureRecognizer.handleTapDown.<anonymous closure> (package:flutter/src/gestures/tap.dart:580)
flutter: #11     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182)
flutter: #12     TapGestureRecognizer.handleTapDown (package:flutter/src/gestures/tap.dart:580)
flutter: #13     BaseTapGestureRecognizer._checkDown (package:flutter/src/gestures/tap.dart:287)
flutter: #14     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:265)
flutter: #15     GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:251)
flutter: #16     GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:232)
flutter: (elided 10 frames from dart:async)

**Comment by zathras** [comment]
Thanks for finding this!  I was able to reproduce, with no stored program in memory.

I'm pretty sure the fix will be easy.  Let me know if this bug is annoying, and you need a new Linux build...  It just takes some time for me to turn the crank on a new build.  If you can build yourself, or if the bug isn't all that annoying, I'll probably hold off on spinning up a new release, maybe even for a couple of months, to see if any other issues come up that can be swept into a release.

Either way, I'll probably put back the source for a fix in a day or two.

**Comment by zathras** [comment]
Fixed by https://github.com/zathras/jrpn/commit/d79761d4d622b301952e4335a3a8fb37360c2164
